server:
  port: 8888

spring.datasource.url: "jdbc:mysql://120.79.5.223:3306/lobby?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false"
spring.datasource.username: "root"
spring.datasource.password: "lxz123qwe"

lobby.redis.database: 10
lobby.redis.host: "120.79.5.223"
lobby.redis.port: 6379
lobby.redis.maxIdle: 1
lobby.redis.maxTotal: 10
lobby.redis.maxWaitMillis: 1500
lobby.redis.password: "lxz123qwe"
lobby.redis.timeout: 1500
lobby.redis.usePool: true

logRootPath: "/game/logs"
  